print(chr(ord('W')-ord('E')+65))
print(chr((ord('Y')-ord('E'))%26+65))
print(chr(ord('R')-ord('E')+65))
print(chr((ord('H')-ord('O'))%26+65))
print(chr((ord('D')-ord('E'))%26+65))
print(chr((ord('L')-ord('R'))%26+65))